export const AUTH_LOGIN_INIT = 'AUTH_LOGIN_INIT'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'

export const AUTH_REGISTER_INIT = 'AUTH_REGISTER_INIT'
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_INIT'
