export const AUTH_LOGIN_INIT = 'AUTH_LOGIN_INIT'
export const AUTH_LOGIN_START = 'AUTH_LOGIN_START'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL'